root:
    path: /
    controller: App\Controller\DefaultController::show
json:
    path: /json
    controller: App\Controller\DefaultController::releaseJson
version:
    path: /version/{version}
    controller: App\Controller\DefaultController::showVersion
releasenotes:
    path: /release-notes
    controller: App\Controller\DefaultController::releaseNotes
release-notes-for-version:
    path: /release-notes/{version}
    controller: App\Controller\DefaultController::releaseNotes
legacy-release-notes-for-version:
    path: /release-notes/{folder}/{version}
    controller: App\Controller\DefaultController::releaseNotes
specificversion:
    path: /{requestedVersion}
    controller: App\Controller\DefaultController::download
versionandformat:
    path: /{requestedVersion}/{requestedFormat}
    controller: App\Controller\DefaultController::download